language: node_js
services:
- postgresql
addons:
  postgresql: '10.0'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "$(jq -r '.engines.yarn' package.json)"
- export PATH="$HOME/.yarn/bin:$PATH"
# - sudo mount -o remount,size=50% /var/ramfs
cache: yarn
install: yarn --frozen-lockfile
script:
- yarn lint
- yarn test
